cameras:
  - name: Camera 1
    ip: 192.168.1.100
    port: 52381
  - name: Camera 2
    ip: 192.168.1.101
    port: 52381
  - name: Camera 3
    ip: 192.168.1.102
    port: 52381
joystick:
  x_pin: 0
  y_pin: 1
  zoom_pin: 2
  deadzone: 0.1
gamepad:
  mapping:
    pan_axis: 0
    tilt_axis: 1
    zoom_axis: 3
    invert_pan: false
    invert_tilt: false
    invert_zoom: false
    deadzone: 0.1
    buttons:
      zoom_in: 0
      zoom_out: 1
      stop: 2
      preset_store_toggle: 3